language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - pip install mock==1.0
  - pip install coverage
  - pip install nose
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install pathlib2==2.1.0; fi
script:
  - python setup.py install
  - nosetests --with-coverage --cover-package=beastling
before_install:
  pip install codecov
after_success:
  codecov

